{{- $secret := lookup "v1" "Secret" .Release.Namespace "datahub-encryption-secrets" -}}
{{- if not $secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: "datahub-encryption-secrets"
type: Opaque
data:
  encryption_key_secret: {{ randAlphaNum 32 | b64enc | quote }}
{{- end -}}