apiVersion: v2
name: datahub-prerequisites
description: A Helm chart for packages that Datahub depends on
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.6
dependencies:
  - name: elasticsearch
    version: 7.16.2
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  # This chart deploys an enterprise version of neo4j that requires commercial license
  - name: neo4j
    version: 4.2.2-1
    repository: https://neo4j-contrib.github.io/neo4j-helm/
    condition: neo4j.enabled
  # This chart deploys a community version of neo4j
  - name: neo4j-community
    version: 1.2.5
    repository: https://equinor.github.io/helm-charts/charts/
    condition: neo4j-community.enabled
  - name: mysql
    version: 8.5.4
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  # This chart deploys an enterprise version of kafka that requires commercial license
  # Note, Schema registry and kafka rest proxy do not require the commercial license
  - name: cp-helm-charts
    version: 0.6.1
    repository: https://klarrio-kpn-rdc.github.io/cp-helm-charts/
    condition: cp-helm-charts.enabled
  # This chart deploys a community version of kafka
  # TODO replace this with reference to Strimzi cluster
#  - name: kafka
#    version: 12.17.4
#    repository: https://charts.bitnami.com/bitnami
#    condition: kafka.enabled
maintainers:
  - name: DataHub
    email: datahub@acryl.io
