{{- if and .Values.global.datahub.scheduler.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datahub-scheduler.serviceAccountName" . }}
  labels:
    {{- include "datahub-scheduler.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
